services:
  chatgpt_qa:
    build:
      context: .
      dockerfile: environment/Dockerfile
      network: "host"
    volumes:
      - ..:/app:cached
    tty: true
    user: vscode
    network_mode: host
    
  